export const DB_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID;
export const IDEAS_COLLECTION = process.env.NEXT_PUBLIC_APPWRITE_IDEAS_COLLECTION_ID;
export const CANVAS_COLLECTION = process.env.NEXT_PUBLIC_APPWRITE_CANVAS_COLLECTION_ID;
export const VALIDATION_COLLECTION = process.env.NEXT_PUBLIC_APPWRITE_VALIDATION_COLLECTION_ID;
export const ROADMAP_COLLECTION = process.env.NEXT_PUBLIC_APPWRITE_ROADMAP_COLLECTION_ID;
export const PITCH_DECK_COLLECTION = process.env.NEXT_PUBLIC_APPWRITE_PITCH_COLLECTION_ID;
export const USERS_COLLECTION = process.env.NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID;